-- =============================================================================
-- 001_init_schema.sql — DEVRE DIŞI BIRAKILDI
-- =============================================================================
-- Bu dosyanın tüm içeriği 000003_create_orders_and_outbox_events.up.sql
-- dosyasına taşınmıştır.
--
-- Docker Compose initdb dosyaları alfabetik sırayla çalıştırır:
--   000003_* → önce çalışır, tam şemayı oluşturur
--   001_*    → bu dosya (no-op)
--   002_*    → bu dosya (no-op)
--
-- Tek şema kaynağı: 000003_create_orders_and_outbox_events.up.sql
-- =============================================================================
